apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Relase.Name }}-todo-delete-tasks-api"
spec:
  replicas: {{ .Values.delete-task.replicas }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-todo-delete-tasks-api"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-todo-delete-tasks-api"
    spec:
      containers:
      - name: "{{ .Release.Name }}-todo-delete-tasks-api"
        image: "{{ .Values.common.containerResgistryURL }}/{{ .Values.delete-task.image.name }}:{{ .Values.delete-task.image.tag }}"
        ports:
        - containerPort: {{ .Values.delete-task.port }}
        env:
          - name: CONNECTION_STRING
            value: {{ .Values.delete-task.connectionString }}