apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Relase.Name }}-todo-delete-task-api-ingress"
spec:
  ingressClassName: {{ .Values.common.ingressClassName }}
  rules:
    - host: {{ .Values.delete-task.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: "{{ .Release.Name }}-todo-delete-tasks-api-service"
                port:
                  number: {{ .Values.delete.task.servicePort }}
