common:
  containerRegistryURL: todoappacr001.azurecr.io
  ingressClassName: azure-application-gateway

ui:
  ingress: 
    host: ui.applicationtesting.online
  replicas: 2
  image:
    name: todo-ui
    tag: v4
  port: 80
  servicePort: 80