apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-todo-get-tasks-api"
spec:
  replicas: {{ .Values.get-tasks.replicas }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-todo-get-tasks-api"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-todo-get-tasks-api"
    spec:
      containers:
      - name: "{{ .Release.Name }}-todo-get-tasks-api"
        image: "{{ .Values.common.containerRegistryURL }}/{{ .Values.get-tasks.image.name }}:{{ .Values.get-tasks.image.tag }}"
        ports:
        - containerPort: {{ .Values.get-tasks.port }}
        env:
          - name: CONNECTION_STRING
            value: {{ .Values.get-tasks.connectionString }}


