apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-todo-get-task-api-ingress"
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
    - host: {{ .Values.getTasks.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: "{{ .Release.Name }}-todo-get-tasks-api-service"
                port:
                  number: {{ .Values.getTasks.servicePort }}
