apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-todo-get-tasks-api-service"
spec:
  type: ClusterIP
  selector:
    app: "{{ .Release.Name }}-todo-get-tasks-api"
  ports:
    - port: {{ .Values.get-tasks.port }}
      targetPort: {{ .Values.get-tasks.servicePort }}
