apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-todo-add-tasks-api"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-todo-add-tasks-api"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-todo-add-tasks-api"
    spec:
      containers:
      - name: "{{ .Release.Name }}-todo-add-tasks-api"
        image: "{{ .Values.common.containerRegistryURL }}/{{ .Values.add-task.image.name }}:{{ .Values.add-task.image.tag }}"
        ports:
        - containerPort: {{ .Values.add-task.port }}
        env:
          - name: CONNECTION_STRING
            value: "{{ .Values.add-task.connectionString }}"