apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-todo-add-tasks-api-service"
spec:
  type: ClusterIP
  selector:
    app: "{{ .Release.Name }}-todo-add-tasks-api"
  ports:
  - port: {{ .Values.add-task.servicePort }}
    targetPort: {{ .Values.add-task.port }}
