apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-todo-ui-ingress"
spec:
  ingressClassName: {{ .Values.common.ingressClassName }}
  rules:
    - host: {{ .Values.ui.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: "{{ .Release.Name }}-todo-ui-service"
                port:
                  number: {{ .Values.ui.servicePort }}